name: Scores Refresh Cron

on:
  # GitHub schedules run at a minimum granularity of ~5 minutes
  schedule:
    - cron: '*/5 * * * *'
  # manual run button in the Actions tab
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Call Supabase Edge Function (scores-refresh)
        env:
          SUPABASE_FUNCTION_URL: ${{ secrets.SUPABASE_FUNCTION_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # 3 quick retries to ride out transient network hiccups
          for i in 1 2 3; do
            CODE=$(curl -sS -o resp.json -w "%{http_code}" -X POST \
              "$SUPABASE_FUNCTION_URL" \
              -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
              -H "Content-Type: application/json" \
              -d '{}') || true
            echo "HTTP $CODE"
            cat resp.json || true
            if [ "$CODE" -ge 200 ] && [ "$CODE" -lt 300 ]; then
              exit 0
            fi
            sleep 10
          done
          echo "Failed after retries"; exit 1
