name: Score latest (cron)

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes (UTC)
  workflow_dispatch: {}     # allow manual run from Actions tab

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call production scoring endpoint
        run: curl -fsS -X GET "$PRODUCTION_URL/api/cron/score-latest"
        env:
          PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
